### ISSUE TITLE
unexpected crashes

### ISSUE THREAD

**Issue by chuckiton** [hrfee/jfa-go#230]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**
jfa-go crashes sporadically with no warning.

Describe the problem, and what you would expect if it isn't clear already.

**To Reproduce**
run jfa-go as a systemd service on bare metal on debian 11 on rpi 4b 4gb.

**Logs**
```2022/11/04 18:17:59 Using internal storage
jfa-go version: 0.4.0 (c6fc576)
Socket: /tmp/jfa-go.sock
[INFO] 18:18:00  Using Jellyfin server type

main.go:436: Failed to authenticate with Jellyfin @ "CENSORED" (0): Post "CENSORED": dial tcp 192.168.1.222:8096: connect: network is unreachable
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x78
main.Exit({0x82bbc8, 0x461be38})
	/drone/src/exit.go:57 +0x2e8
github.com/hrfee/jfa-go/logger.(*Logger).Fatalf(0x2f86e58, {0x910b94, 0x34}, {0x2d0fe74, 0x3, 0x3})
	/drone/src/logger/logger.go:128 +0x140
main.start(0x0, 0x1)
	/drone/src/main.go:436 +0x30b0
main.main()
	/drone/src/main.go:753 +0x5c4
```

**Configuration**
nothing unusual 

**Platform/Version**

jfa-go version: 0.4.0 (c6fc576)

**Comment by ben-ba** [comment]
which ip does your Jellyfin instance have?
