### ISSUE TITLE
 Failed to authenticate with Jellyfin @ "CENSORED" (0): Post "CENSORED": context deadline exceeded (Client.Timeout exceeded while awaiting headers) goroutine 14 [running]:

### ISSUE THREAD

**Issue by zaourzag** [hrfee/jfa-go#276]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**
unable to connect to jellyfin

**To Reproduce**
take a normally working config, put it in the latest release.
expect it to work, it does not.
**Logs**

```

                        An attempt has been made to remove sensitive info, but make sure to check yourself.
                        2023/07/06 21:12:34 Using internal storage
jfa-go version: git (f729606) TrayIcon
Socket: C:\Users\<redacted>\AppData\Local\Temp\jfa-go.sock
[INFO] 21:12:36  Connected to DB "CENSORED"
[INFO] 21:12:36  Using Jellyfin server type

main.go:396: Failed to authenticate with Jellyfin @ "CENSORED" (0): Post "CENSORED": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
goroutine 14 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.Exit({0x1eddf20, 0xc001084180})
	/drone/src/exit.go:73 +0x2e5
github.com/hrfee/jfa-go/logger.(*Logger).Fatalf(0xc000333860, {0x209ff1a?, 0x34?}, {0xc0000b1c80?, 0x3?, 0x3?})
	/drone/src/logger/logger.go:128 +0x135
main.start(0x0, 0x0?)
	/drone/src/main.go:396 +0x2176
created by main.onReady
	/drone/src/tray.go:64 +0x325

```

**Platform/Version**
windows 10 Pro, most recent nightly build but was getting this on most recent stable build.

**Comment by hrfee** [comment]
Copied from #281:

Not sure if you still use jfa-go since its been so long, but f6fdd41 adds a retry mechanism, 6 attempts to connect to Jellyfin are made, 10 seconds apart. If this isn't long enough, its configurable in the advanced settings section.
