### ISSUE TITLE
Trying to add a User Profile with homescreen layout fails

### ISSUE THREAD

**Issue by rigrig** [hrfee/jfa-go#99]
**Bug Description**

The "Add Profile" dialog gives an error if I leave "Store homescreen layout" checked.

**To Reproduce**

1. Go to `/settings`
2. Open "User Profiles"
3. Click the "Create" button
4. Fill in the name, select an existing profile, leave "Store homescreen layout" checked
5. Click the "Create" button

Expected result: new profile is created   
Actual result: `Error: Failed to create profile "Default"`

**Logs**

Console log for the POST request to `/profiles`:
```json
{"response":"","error":"Couldn't get displayprefs"}
```
<details><summary>Docker log (from a docker-compose with both Jellyfin and jfa-go):</summary>

```
[18:41:51] [INF] Reissuing access token: ************REDACTED************
[18:42:07] [ERR] Failed executing DbCommand (1ms) [Parameters=[@p0='?', @p1='?' (Size = 4), @p2='?', @p3='?', @p4='?', @p5='?', @p6='?', @p7='?', @p8='?', @p9='?', @p10='?', @p11='?', @p12='?'], CommandType='Text', CommandTimeout='30']
INSERT INTO "DisplayPreferences" ("ChromecastVersion", "Client", "DashboardTheme", "EnableNextVideoInfoOverlay", "IndexBy", "ItemId", "ScrollDirection", "ShowBackdrop", "ShowSidebar", "SkipBackwardLength", "SkipForwardLength", "TvHome", "UserId")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12);
SELECT "Id"
FROM "DisplayPreferences"
WHERE changes() = 1 AND "rowid" = last_insert_rowid();
[18:42:07] [ERR] An exception occurred in the database while saving changes for context type 'Jellyfin.Server.Implementations.JellyfinDb'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
[18:42:07] [ERR] Error processing request. URL GET /DisplayPreferences/usersettings.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Users.DisplayPreferencesManager.SaveChanges()
   at Jellyfin.Api.Controllers.DisplayPreferencesController.GetDisplayPreferences(String displayPreferencesId, Guid userId, String client)
   at lambda_method885(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
```
</details>

**Platform/Version**
Running a docker-compose with both Jellyfin and jfa-go:   
jfa-go: 0.3.4 (Commit b2b5083)
Jellyfin: 10.7.5

**Notes**
There already was an existing profile based on the same user, but creating new accounts from it failed. So I deleted the profile and tried to recreate it, when I ran into this.

**Comment by hrfee** [comment]
Could you send the logs of jfa-go (with debug mode enabled) when you try to create the profile?

Also i can't seem to reproduce the issue, Could you run `docker inspect <your jellyfin container name> | grep "Image"` and send the output? That way i can test on the exact Jellyfin server image you're using.

**Comment by rigrig** [comment]
Doh, sorry.  Seems I somehow thought those jellyfin docker logs also included jfa-go logs...
This is what shows up when I press the "Create" button:
```
[DEBUG] 22:22:54 auth.go:89: Auth succeeded
[INFO] 22:22:54  Profile creation requested
[DEBUG] 22:22:54 api.go:977: Creating profile from user "profile-template"
[ERROR] 22:22:54 api.go:982: Failed to get DisplayPrefs (500): <nil>
[GIN/DEBUG] 22:22:54: POST(/profiles) => 500 in 37.24627ms; 
```

Docker images:
```sh
$ docker inspect jellyfin | grep "Image"
        "Image": "sha256:680139573562f7110591987298ad56e0c1691408d76d1521964d24f717b820c3",
            "Image": "jellyfin/jellyfin",
$ docker inspect jellyfin-jfa | grep "Image"
        "Image": "sha256:c0eb374a6fc5455307c29218dc8db267f1b6295a76cd9a4632c46892c07fc582",
            "Image": "hrfee/jfa-go",
```

<details><summary>My complete `docker-compose.yml`, in case it helps</summary>

```yaml
version: "2.1"  
services:  
  jellyfin:  
    container_name: jellyfin
    #image: jellyfin/jellyfin:unstable
    image: jellyfin/jellyfin
    #image: jellyfin/jellyfin@sha256:010e197041008ffa00d2c94f31b87d64666e9a93a9cf3314ce7f87134b801a5f
    user: 1026:100
    group_add:
      - 65537 # video, for /dev/dri devices
    network_mode: "host"  
    volumes:  
      - ./config:/config
      - ./cache:/cache
      - ./transcodes:/transcodes
      - /volume1/Media:/media
    devices: # for HW acceleration
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

  jfa-go:
    container_name: jellyfin-jfa
    #image: hrfee/jfa-go:unstable
    image: hrfee/jfa-go
    # explicitly specify subnet, so we can whitelist it in jellyfin
    networks:
      jfa:
        ipv4_address: 192.168.3.100
    user: 1026:100
    volumes:
      - ./jfa-config:/data
      - ./config:/jf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8097:8056
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

networks:
  jfa:
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
```
</details>

**Comment by hrfee** [comment]
I'm running the exact same version as you and it doesn't occur for me, and this shouldn't be a jfa-go issue as it's just requesting a users displayprefs. Someone had a similar problem before and a restart of Jellyfin fixed it. Could you try restarting it?

**Comment by rigrig** [comment]
Huh, that fixed it.
Which is weird, as I already restarted it earlier today (some time before trying to create the profile), so apparently I somehow broke it...

"Restarting fixes it" is good enough for me though (and I guess there's not much point in trying things out now that it works anyway).
